/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings { 'transactionSystemEnabled' : boolean }
export interface NotificationWithRead {
  'id' : string,
  'isGlobal' : boolean,
  'title' : string,
  'body' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export interface SupportTicket {
  'id' : string,
  'status' : SupportTicketStatus,
  'adminReply' : string,
  'subject' : string,
  'userId' : string,
  'createdAt' : bigint,
  'message' : string,
}
export type SupportTicketStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'replied' : null };
export interface Transaction {
  'id' : string,
  'status' : TransactionStatus,
  'provider' : string,
  'userId' : string,
  'createdAt' : bigint,
  'recipient' : string,
  'txType' : TransactionType,
  'amount' : number,
  'slipData' : string,
}
export type TransactionStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export type TransactionType = { 'cashOut' : null } |
  { 'bankTransfer' : null } |
  { 'addMoney' : null } |
  { 'recharge' : null } |
  { 'savings' : null } |
  { 'sendMoney' : null } |
  { 'payBill' : null };
export interface UserProfile { 'name' : string, 'mobile' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveKYC' : ActorMethod<[string, string], Result>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTransaction' : ActorMethod<[string, string], Result>,
  'changePIN' : ActorMethod<[string, string, string], Result>,
  'completeTransaction' : ActorMethod<[string, string], Result>,
  'createAnnouncement' : ActorMethod<[string, string, string], Result>,
  'createSupportTicket' : ActorMethod<[string, string, string], Result>,
  'createTransaction' : ActorMethod<
    [string, TransactionType, number, string, string],
    Result
  >,
  'getAllTickets' : ActorMethod<[string], Array<SupportTicket>>,
  'getAllTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getAppSettings' : ActorMethod<[string], AppSettings>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUser' : ActorMethod<[string], Result>,
  'getUserNotifications' : ActorMethod<[string], Array<NotificationWithRead>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTickets' : ActorMethod<[string], Array<SupportTicket>>,
  'getUserTransactions' : ActorMethod<[string], Array<Transaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[string, string, string], Result>,
  'markNotificationRead' : ActorMethod<[string, string], Result>,
  'registerUser' : ActorMethod<[string, string, string, string], Result>,
  'rejectKYC' : ActorMethod<[string, string], Result>,
  'replyToTicket' : ActorMethod<[string, string, string], Result>,
  'resetUserDevice' : ActorMethod<[string, string, string], Result>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTransactionSystemEnabled' : ActorMethod<[string, boolean], Result>,
  'setUserBalance' : ActorMethod<[string, string, number], Result>,
  'submitKYC' : ActorMethod<[string, string, string, string, string], Result>,
  'updateDeviceId' : ActorMethod<[string, string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];