/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'cashOut' : IDL.Null,
  'bankTransfer' : IDL.Null,
  'addMoney' : IDL.Null,
  'recharge' : IDL.Null,
  'savings' : IDL.Null,
  'sendMoney' : IDL.Null,
  'payBill' : IDL.Null,
});
export const SupportTicketStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'replied' : IDL.Null,
});
export const SupportTicket = IDL.Record({
  'id' : IDL.Text,
  'status' : SupportTicketStatus,
  'adminReply' : IDL.Text,
  'subject' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
});
export const TransactionStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : TransactionStatus,
  'provider' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'recipient' : IDL.Text,
  'txType' : TransactionType,
  'amount' : IDL.Float64,
  'slipData' : IDL.Text,
});
export const AppSettings = IDL.Record({
  'transactionSystemEnabled' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'mobile' : IDL.Text,
});
export const NotificationWithRead = IDL.Record({
  'id' : IDL.Text,
  'isGlobal' : IDL.Bool,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveKYC' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelTransaction' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'changePIN' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'completeTransaction' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'createSupportTicket' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'createTransaction' : IDL.Func(
      [IDL.Text, TransactionType, IDL.Float64, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'getAllTickets' : IDL.Func([IDL.Text], [IDL.Vec(SupportTicket)], ['query']),
  'getAllTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getAppSettings' : IDL.Func([IDL.Text], [AppSettings], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUser' : IDL.Func([IDL.Text], [Result], ['query']),
  'getUserNotifications' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NotificationWithRead)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTickets' : IDL.Func([IDL.Text], [IDL.Vec(SupportTicket)], ['query']),
  'getUserTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'markNotificationRead' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'rejectKYC' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'replyToTicket' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'resetUserDevice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTransactionSystemEnabled' : IDL.Func([IDL.Text, IDL.Bool], [Result], []),
  'setUserBalance' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [Result], []),
  'submitKYC' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'updateDeviceId' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'cashOut' : IDL.Null,
    'bankTransfer' : IDL.Null,
    'addMoney' : IDL.Null,
    'recharge' : IDL.Null,
    'savings' : IDL.Null,
    'sendMoney' : IDL.Null,
    'payBill' : IDL.Null,
  });
  const SupportTicketStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'replied' : IDL.Null,
  });
  const SupportTicket = IDL.Record({
    'id' : IDL.Text,
    'status' : SupportTicketStatus,
    'adminReply' : IDL.Text,
    'subject' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'message' : IDL.Text,
  });
  const TransactionStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : TransactionStatus,
    'provider' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'recipient' : IDL.Text,
    'txType' : TransactionType,
    'amount' : IDL.Float64,
    'slipData' : IDL.Text,
  });
  const AppSettings = IDL.Record({ 'transactionSystemEnabled' : IDL.Bool });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'mobile' : IDL.Text });
  const NotificationWithRead = IDL.Record({
    'id' : IDL.Text,
    'isGlobal' : IDL.Bool,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveKYC' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelTransaction' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'changePIN' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'completeTransaction' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'createSupportTicket' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'createTransaction' : IDL.Func(
        [IDL.Text, TransactionType, IDL.Float64, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'getAllTickets' : IDL.Func([IDL.Text], [IDL.Vec(SupportTicket)], ['query']),
    'getAllTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getAppSettings' : IDL.Func([IDL.Text], [AppSettings], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUser' : IDL.Func([IDL.Text], [Result], ['query']),
    'getUserNotifications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NotificationWithRead)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTickets' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SupportTicket)],
        ['query'],
      ),
    'getUserTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'markNotificationRead' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'rejectKYC' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'replyToTicket' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'resetUserDevice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTransactionSystemEnabled' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [Result],
        [],
      ),
    'setUserBalance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [Result],
        [],
      ),
    'submitKYC' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'updateDeviceId' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };